import type { WardrobeItem } from "@/types/wardrobe";

export const mockOwnedItems: WardrobeItem[] = [
  {
    id: "owned-001",
    name: "Black Blazer",
    status: "owned",
    category: "outerwear",
    colorFamily: "black",
    colorName: "Black",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "work", "elevated"],
    notes: "A reliable office layer for polished outfits.",
    stylingNotes: "Best when softened with cream, camel, denim, or warm brown so it does not feel too harsh.",
  },
  {
    id: "owned-002",
    name: "Beige Blazer",
    status: "owned",
    category: "outerwear",
    colorFamily: "beige",
    colorName: "Warm Beige",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "minimal", "work"],
    notes: "Light neutral blazer for office formulas.",
    stylingNotes: "Works best with chocolate, camel, denim, and gold-toned accessories.",
  },
  {
    id: "owned-003",
    name: "Light Rose Blazer",
    status: "owned",
    category: "outerwear",
    colorFamily: "statement",
    colorName: "Soft Rose",
    size: "M",
    brand: "Acloset",
    vibes: ["elevated", "statement", "work"],
    notes: "Soft feminine blazer that needs grounding.",
    stylingNotes: "Keep the rest of the look warm and quiet so the rose reads intentional.",
  },
  {
    id: "owned-004",
    name: "Warm Brown Blazer Vest",
    status: "owned",
    category: "outerwear",
    colorFamily: "brown",
    colorName: "Warm Brown",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "work", "elevated"],
    notes: "Sleeveless tailored vest for warm office days.",
    stylingNotes: "Wear open to create a vertical line and keep the outfit breathable.",
  },
  {
    id: "owned-005",
    name: "White Cropped Jacket",
    status: "owned",
    category: "outerwear",
    colorFamily: "white",
    colorName: "Warm White",
    size: "M",
    brand: "Acloset",
    vibes: ["casual", "elevated", "tropical"],
    notes: "Current light jacket option.",
    stylingNotes: "Use sparingly with warm colors so it does not feel too stark.",
  },
  {
    id: "owned-006",
    name: "Black Cardigan",
    status: "owned",
    category: "outerwear",
    colorFamily: "black",
    colorName: "Black",
    size: "M",
    brand: "Acloset",
    vibes: ["minimal", "casual", "work"],
    notes: "Light layering piece for cooler spaces.",
    stylingNotes: "Good for AC days, but not a color-building piece.",
  },
  {
    id: "owned-007",
    name: "Cream Camisole",
    status: "owned",
    category: "top",
    colorFamily: "cream",
    colorName: "Cream",
    size: "M",
    brand: "Acloset",
    vibes: ["minimal", "classic", "elevated"],
    notes: "Soft base layer for blazers and cardigans.",
    stylingNotes: "A strong base with chocolate, olive, camel, denim, and burgundy.",
  },
  {
    id: "owned-008",
    name: "Black Bodysuit",
    status: "owned",
    category: "top",
    colorFamily: "black",
    colorName: "Black",
    size: "M",
    brand: "Acloset",
    vibes: ["minimal", "classic", "casual"],
    notes: "Reliable fitted base top.",
    stylingNotes: "Use when the bottom or outerwear brings warmth and softness.",
  },
  {
    id: "owned-009",
    name: "Brown Tank Top",
    status: "owned",
    category: "top",
    colorFamily: "brown",
    colorName: "Chocolate Brown",
    size: "M",
    brand: "Acloset",
    vibes: ["minimal", "casual", "tropical"],
    notes: "Warm neutral tank for PR weather.",
    stylingNotes: "Pairs easily with denim, beige, camel, cream, and gold accessories.",
  },
  {
    id: "owned-010",
    name: "Burgundy Crop Top",
    status: "owned",
    category: "top",
    colorFamily: "burgundy",
    colorName: "Warm Burgundy",
    size: "M",
    brand: "Acloset",
    vibes: ["statement", "casual", "tropical"],
    notes: "Color base that still fits Dark Autumn.",
    stylingNotes: "Good with brown, denim, camel, and cream for intentional color.",
  },
  {
    id: "owned-011",
    name: "Gray Fitted Tee",
    status: "owned",
    category: "top",
    colorFamily: "statement",
    colorName: "Warm Gray",
    size: "M",
    brand: "Acloset",
    vibes: ["casual", "minimal"],
    notes: "Casual neutral tee.",
    stylingNotes: "Use as a soft basic, but avoid making the outfit too cool-toned.",
  },
  {
    id: "owned-012",
    name: "White Button Shirt",
    status: "owned",
    category: "top",
    colorFamily: "white",
    colorName: "White",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "work", "elevated"],
    notes: "Classic button-down option.",
    stylingNotes: "Warm it up with brown belts, camel shoes, or gold jewelry.",
  },
  {
    id: "owned-013",
    name: "Casual Striped Button Shirt",
    status: "owned",
    category: "top",
    colorFamily: "blue",
    colorName: "Muted Blue Stripe",
    size: "M",
    brand: "Acloset",
    vibes: ["casual", "classic"],
    notes: "Casual button shirt, less office-elegant.",
    stylingNotes: "Best for Friday denim or relaxed office days.",
  },
  {
    id: "owned-014",
    name: "Black Tube Top",
    status: "owned",
    category: "top",
    colorFamily: "black",
    colorName: "Black",
    size: "M",
    brand: "Acloset",
    vibes: ["casual", "minimal", "tropical"],
    notes: "Simple warm-weather base.",
    stylingNotes: "Needs elevated bottoms, belt, or accessories to avoid feeling too basic.",
  },
  {
    id: "owned-015",
    name: "Cream Knit Top",
    status: "owned",
    category: "top",
    colorFamily: "cream",
    colorName: "Soft Cream",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "minimal", "work"],
    notes: "Soft neutral top for polished formulas.",
    stylingNotes: "Very useful under blazer vest or warm neutral blazer.",
  },
  {
    id: "owned-016",
    name: "Brown Wide Leg Pants",
    status: "owned",
    category: "bottom",
    colorFamily: "brown",
    colorName: "Chocolate Brown",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "work", "elevated"],
    notes: "Strong foundation bottom.",
    stylingNotes: "One of the best base pieces for Dark Autumn office outfits.",
  },
  {
    id: "owned-017",
    name: "Dark Denim Straight Leg Jeans",
    status: "owned",
    category: "bottom",
    colorFamily: "denim",
    colorName: "Dark Denim",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "casual", "work"],
    notes: "Friday office and casual polish essential.",
    stylingNotes: "Dark wash keeps denim elevated enough for polished casual outfits.",
  },
  {
    id: "owned-018",
    name: "Black Straight Leg Pants",
    status: "owned",
    category: "bottom",
    colorFamily: "black",
    colorName: "Black",
    size: "M",
    brand: "Acloset",
    vibes: ["work", "classic", "minimal"],
    notes: "Work-safe neutral pant.",
    stylingNotes: "Use with camel, cream, burgundy, or olive to avoid all-black repetition.",
  },
  {
    id: "owned-019",
    name: "Beige Wide Leg Pants",
    status: "owned",
    category: "bottom",
    colorFamily: "beige",
    colorName: "Warm Beige",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "work", "minimal"],
    notes: "Light warm neutral bottom.",
    stylingNotes: "Works well with brown, cream, burgundy, and olive.",
  },
  {
    id: "owned-020",
    name: "Dark Denim Wide Leg Jeans",
    status: "owned",
    category: "bottom",
    colorFamily: "denim",
    colorName: "Dark Denim",
    size: "M",
    brand: "Acloset",
    vibes: ["casual", "classic", "elevated"],
    notes: "Wide-leg denim option.",
    stylingNotes: "Good for balancing fitted tops and cropped jackets.",
  },
  {
    id: "owned-021",
    name: "Black Neutral Dress",
    status: "owned",
    category: "dress",
    colorFamily: "black",
    colorName: "Black",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "minimal", "elevated"],
    notes: "Simple black dress.",
    stylingNotes: "Needs warm accessories to avoid feeling flat.",
  },
  {
    id: "owned-022",
    name: "Neutral Knit Dress",
    status: "owned",
    category: "dress",
    colorFamily: "beige",
    colorName: "Warm Neutral",
    size: "M",
    brand: "Acloset",
    vibes: ["classic", "minimal", "elevated"],
    notes: "Soft neutral dress option.",
    stylingNotes: "Best with brown belt, gold jewelry, and warm sandals.",
  },
  {
    id: "owned-023",
    name: "Dark Brown Loafers",
    status: "owned",
    category: "shoes",
    colorFamily: "brown",
    colorName: "Dark Brown",
    size: "8",
    brand: "Acloset",
    vibes: ["classic", "work", "elevated"],
    notes: "Polished shoe for work formulas.",
    stylingNotes: "Key shoe for making neutral outfits look finished.",
  },
  {
    id: "owned-024",
    name: "Adidas Tokyo Sneakers",
    status: "owned",
    category: "shoes",
    colorFamily: "statement",
    colorName: "Sporty Statement",
    size: "8",
    brand: "Adidas",
    vibes: ["casual", "statement"],
    notes: "Sporty casual shoe.",
    stylingNotes: "Best for casual polish or weekend looks, not core office outfits.",
  },
  {
    id: "owned-025",
    name: "Neutral Sandals",
    status: "owned",
    category: "shoes",
    colorFamily: "beige",
    colorName: "Warm Beige",
    size: "8",
    brand: "Acloset",
    vibes: ["tropical", "casual", "minimal"],
    notes: "Warm-weather sandal option.",
    stylingNotes: "Useful for PR, but needs polished bag/accessories to feel elevated.",
  },
  {
    id: "owned-026",
    name: "Brown Work Tote",
    status: "owned",
    category: "bag",
    colorFamily: "brown",
    colorName: "Espresso Brown",
    brand: "Acloset",
    vibes: ["classic", "work", "elevated"],
    notes: "Structured work bag.",
    stylingNotes: "Adds polish to simple formulas.",
  },
  {
    id: "owned-027",
    name: "Cream Shoulder Bag",
    status: "owned",
    category: "bag",
    colorFamily: "cream",
    colorName: "Cream",
    brand: "Acloset",
    vibes: ["classic", "minimal", "elevated"],
    notes: "Light neutral bag.",
    stylingNotes: "Good with darker outfits when you need contrast.",
  },
  {
    id: "owned-028",
    name: "Brown Leather Belt",
    status: "owned",
    category: "accessory",
    colorFamily: "brown",
    colorName: "Warm Brown",
    brand: "Acloset",
    vibes: ["classic", "elevated"],
    notes: "Core styling accessory.",
    stylingNotes: "Important for defining waist and finishing outfits.",
  },
  {
    id: "owned-029",
    name: "Gold Hoop Earrings",
    status: "owned",
    category: "jewelry",
    colorFamily: "mustard",
    colorName: "Warm Gold",
    brand: "Acloset",
    vibes: ["classic", "elevated", "tropical"],
    notes: "Everyday gold jewelry.",
    stylingNotes: "Works with the Dark Autumn palette and warms up black/white outfits.",
  },
  {
    id: "owned-030",
    name: "Gold Watch",
    status: "owned",
    category: "jewelry",
    colorFamily: "mustard",
    colorName: "Warm Gold",
    brand: "Acloset",
    vibes: ["classic", "work", "elevated"],
    notes: "Daily finishing piece.",
    stylingNotes: "Helps simple outfits feel intentional and polished.",
  },
];
