import type { WishlistItem } from "@/types/wardrobe";

export const mockWishlistItems: WishlistItem[] = [
  {
    id: "wishlist-001",
    name: "Camel Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "camel",
    colorName: "Warm Camel",
    size: "M",
    source: "SHEIN",
    vibes: ["classic", "work", "elevated"],
    decision: "buy-priority",
    duplicateRisk: "low",
    closetGap: "workwear",
    priorityScore: 9,
    outfitPotential: 9,
    notes: "Strong capsule builder. Adds warmth without duplicating black or beige.",
  },
  {
    id: "wishlist-002",
    name: "Burgundy Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "burgundy",
    colorName: "Warm Burgundy",
    size: "M",
    source: "SHEIN",
    vibes: ["classic", "statement", "work"],
    decision: "wishlist",
    duplicateRisk: "low",
    closetGap: "color",
    priorityScore: 8,
    outfitPotential: 8,
    notes: "Adds intentional color and works with brown, cream, camel, denim, and black.",
  },
  {
    id: "wishlist-003",
    name: "Olive Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "olive",
    colorName: "Muted Olive",
    size: "M",
    source: "SHEIN",
    vibes: ["classic", "tropical", "work"],
    decision: "wishlist",
    duplicateRisk: "low",
    closetGap: "color",
    priorityScore: 8,
    outfitPotential: 8,
    notes: "Aligned with Dark Autumn and adds tropical versatility.",
  },
  {
    id: "wishlist-004",
    name: "Statement Blue Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "blue",
    colorName: "Statement Blue",
    size: "M",
    source: "SHEIN",
    vibes: ["statement", "work"],
    decision: "consider",
    duplicateRisk: "medium",
    closetGap: "statement",
    priorityScore: 6,
    outfitPotential: 5,
    notes: "Could be fun, but needs enough outfit combinations before buying.",
  },
];
