import type { WardrobeItem } from "@/types/wardrobe";

export const mockOwnedItems: WardrobeItem[] = [
  {
    id: "owned-001",
    name: "Black Blazer",
    status: "owned",
    category: "outerwear",
    colorFamily: "black",
    colorName: "Black",
    size: "M",
    vibes: ["classic", "work", "elevated"],
    notes: "Useful workwear piece, but black is already heavily represented.",
  },
  {
    id: "owned-002",
    name: "Beige Blazer",
    status: "owned",
    category: "outerwear",
    colorFamily: "beige",
    colorName: "Beige",
    size: "M",
    vibes: ["classic", "minimal", "work"],
    notes: "Neutral blazer. Avoid duplicating similar beige outerwear.",
  },
  {
    id: "owned-003",
    name: "Light Rose Blazer",
    status: "owned",
    category: "outerwear",
    colorFamily: "statement",
    colorName: "Soft Rose",
    size: "M",
    vibes: ["classic", "work"],
    notes: "Existing color blazer. Use carefully because it is softer than ideal Dark Autumn colors.",
  },
  {
    id: "owned-004",
    name: "Warm Brown Blazer Vest",
    status: "owned",
    category: "outerwear",
    colorFamily: "brown",
    colorName: "Warm Brown",
    size: "M",
    vibes: ["classic", "elevated", "work"],
    notes: "Style win: looks better worn open.",
    stylingNotes:
      "Wearing it open creates a vertical line and feels more relaxed, elegant, and polished.",
  },
  {
    id: "owned-005",
    name: "Brown Wide Leg Pants",
    status: "owned",
    category: "bottom",
    colorFamily: "brown",
    colorName: "Chocolate Brown",
    size: "M",
    vibes: ["classic", "work", "elevated"],
    notes: "Already owned. Do not duplicate brown wide leg pants.",
  },
  {
    id: "owned-006",
    name: "Dark Denim Straight Leg Jeans",
    status: "owned",
    category: "bottom",
    colorFamily: "denim",
    colorName: "Dark Denim",
    size: "M",
    vibes: ["classic", "casual"],
    notes: "Good for Friday and Saturday work outfits.",
  },
];
