import type { WishlistItem } from "@/types/wardrobe";

export const mockWishlistItems: WishlistItem[] = [
  {
    id: "wish-001",
    name: "Camel Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "camel",
    colorName: "Warm Camel",
    size: "M",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "work", "elevated"],
    decision: "buy-priority",
    priorityTier: "foundation-buys",
    purchaseOrder: 1,
    duplicateRisk: "low",
    closetGap: "workwear",
    priorityScore: 9,
    outfitPotential: 9,
    closetImpactScore: 10,
    currentPrice: 28.99,
    targetPrice: 22,
    lowestPrice: 25.49,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 31.99 },
      { date: "2026-06-08", price: 29.99 },
      { date: "2026-06-15", price: 28.99 },
    ],
    notes: "The strongest foundation blazer because it lightens the closet without going cold or pastel.",
  },
  {
    id: "wish-002",
    name: "Burgundy Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "burgundy",
    colorName: "Warm Burgundy",
    size: "M",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["work", "statement", "elevated"],
    decision: "wishlist",
    priorityTier: "color-builders",
    purchaseOrder: 2,
    duplicateRisk: "low",
    closetGap: "color",
    priorityScore: 8,
    outfitPotential: 8,
    closetImpactScore: 9,
    currentPrice: 31.49,
    targetPrice: 24,
    lowestPrice: 27.99,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 34.99 },
      { date: "2026-06-08", price: 32.99 },
      { date: "2026-06-15", price: 31.49 },
    ],
    notes: "Adds color while staying rich, warm, and office-ready.",
  },
  {
    id: "wish-003",
    name: "Olive Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "olive",
    colorName: "Muted Olive",
    size: "M",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "work", "tropical"],
    decision: "wishlist",
    priorityTier: "color-builders",
    purchaseOrder: 3,
    duplicateRisk: "low",
    closetGap: "color",
    priorityScore: 8,
    outfitPotential: 8,
    closetImpactScore: 8,
    currentPrice: 26.99,
    targetPrice: 21,
    lowestPrice: 24.99,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 29.99 },
      { date: "2026-06-08", price: 26.99 },
      { date: "2026-06-15", price: 26.99 },
    ],
    notes: "A good Dark Autumn color builder that pairs well with denim, cream, camel, and brown.",
  },
  {
    id: "wish-004",
    name: "Chocolate Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "brown",
    colorName: "Chocolate",
    size: "M",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "work", "elevated"],
    decision: "wishlist",
    priorityTier: "foundation-buys",
    purchaseOrder: 4,
    duplicateRisk: "medium",
    closetGap: "workwear",
    priorityScore: 7,
    outfitPotential: 8,
    closetImpactScore: 8,
    currentPrice: 33.99,
    targetPrice: 25,
    lowestPrice: 30.49,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 36.99 },
      { date: "2026-06-08", price: 34.99 },
      { date: "2026-06-15", price: 33.99 },
    ],
    notes: "Useful, but lower priority than camel because the closet already has many brown/neutral pieces.",
  },
  {
    id: "wish-005",
    name: "Plum Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "plum",
    colorName: "Muted Plum",
    size: "M",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["statement", "work", "elevated"],
    decision: "consider",
    priorityTier: "statement-review",
    purchaseOrder: 5,
    duplicateRisk: "low",
    closetGap: "statement",
    priorityScore: 6,
    outfitPotential: 6,
    closetImpactScore: 7,
    currentPrice: 34.99,
    targetPrice: 24,
    lowestPrice: 31.99,
    priceWatch: false,
    priceHistory: [
      { date: "2026-06-01", price: 36.99 },
      { date: "2026-06-08", price: 34.99 },
      { date: "2026-06-15", price: 34.99 },
    ],
    notes: "Pretty color, but needs enough outfit formulas before buying.",
  },
  {
    id: "wish-006",
    name: "Burgundy Loafers",
    status: "wishlist",
    category: "shoes",
    colorFamily: "burgundy",
    colorName: "Deep Burgundy",
    size: "8",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "work", "statement"],
    decision: "buy-priority",
    priorityTier: "foundation-buys",
    purchaseOrder: 6,
    duplicateRisk: "low",
    closetGap: "shoes",
    priorityScore: 9,
    outfitPotential: 9,
    closetImpactScore: 9,
    currentPrice: 24.99,
    targetPrice: 18,
    lowestPrice: 22.49,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 27.99 },
      { date: "2026-06-08", price: 25.99 },
      { date: "2026-06-15", price: 24.99 },
    ],
    notes: "Shoes are a real gap. Burgundy adds color without feeling random.",
  },
  {
    id: "wish-007",
    name: "Dark Brown Mules",
    status: "wishlist",
    category: "shoes",
    colorFamily: "brown",
    colorName: "Dark Brown",
    size: "8",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "work", "elevated"],
    decision: "wishlist",
    priorityTier: "foundation-buys",
    purchaseOrder: 7,
    duplicateRisk: "low",
    closetGap: "shoes",
    priorityScore: 8,
    outfitPotential: 9,
    closetImpactScore: 8,
    currentPrice: 22.99,
    targetPrice: 17,
    lowestPrice: 20.99,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 25.99 },
      { date: "2026-06-08", price: 22.99 },
      { date: "2026-06-15", price: 22.99 },
    ],
    notes: "Useful shoe for work looks and warm neutral outfits.",
  },
  {
    id: "wish-008",
    name: "Orange Beaded Sandals",
    status: "wishlist",
    category: "shoes",
    colorFamily: "statement",
    colorName: "Caribbean Orange",
    size: "8",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["tropical", "statement", "casual"],
    decision: "consider",
    priorityTier: "statement-review",
    purchaseOrder: 8,
    duplicateRisk: "low",
    closetGap: "tropical",
    priorityScore: 6,
    outfitPotential: 5,
    closetImpactScore: 6,
    currentPrice: 19.99,
    targetPrice: 14,
    lowestPrice: 18.49,
    priceWatch: false,
    priceHistory: [
      { date: "2026-06-01", price: 21.99 },
      { date: "2026-06-08", price: 19.99 },
      { date: "2026-06-15", price: 19.99 },
    ],
    notes: "Fun PR piece, but should only be bought if it creates enough tropical outfits.",
  },
  {
    id: "wish-009",
    name: "Olive Crossbody Bag",
    status: "wishlist",
    category: "bag",
    colorFamily: "olive",
    colorName: "Muted Olive",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "casual", "tropical"],
    decision: "wishlist",
    priorityTier: "color-builders",
    purchaseOrder: 9,
    duplicateRisk: "low",
    closetGap: "accessory",
    priorityScore: 8,
    outfitPotential: 8,
    closetImpactScore: 8,
    currentPrice: 18.99,
    targetPrice: 14,
    lowestPrice: 16.99,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 21.99 },
      { date: "2026-06-08", price: 19.99 },
      { date: "2026-06-15", price: 18.99 },
    ],
    notes: "Adds color in a low-risk way and helps simple outfits look styled.",
  },
  {
    id: "wish-010",
    name: "Camel Structured Bag",
    status: "wishlist",
    category: "bag",
    colorFamily: "camel",
    colorName: "Warm Camel",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "work", "elevated"],
    decision: "wishlist",
    priorityTier: "foundation-buys",
    purchaseOrder: 10,
    duplicateRisk: "low",
    closetGap: "accessory",
    priorityScore: 8,
    outfitPotential: 9,
    closetImpactScore: 8,
    currentPrice: 25.99,
    targetPrice: 19,
    lowestPrice: 23.99,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 27.99 },
      { date: "2026-06-08", price: 25.99 },
      { date: "2026-06-15", price: 25.99 },
    ],
    notes: "A structured warm bag would elevate many simple office looks.",
  },
  {
    id: "wish-011",
    name: "Brown Waist Belt",
    status: "wishlist",
    category: "accessory",
    colorFamily: "brown",
    colorName: "Warm Brown",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "elevated", "work"],
    decision: "buy-priority",
    priorityTier: "foundation-buys",
    purchaseOrder: 11,
    duplicateRisk: "medium",
    closetGap: "accessory",
    priorityScore: 8,
    outfitPotential: 10,
    closetImpactScore: 9,
    currentPrice: 8.99,
    targetPrice: 7,
    lowestPrice: 8.49,
    priceWatch: false,
    priceHistory: [
      { date: "2026-06-01", price: 9.99 },
      { date: "2026-06-08", price: 8.99 },
      { date: "2026-06-15", price: 8.99 },
    ],
    notes: "Belts are high-impact because they define the waist and finish outfits.",
  },
  {
    id: "wish-012",
    name: "Gold Statement Earrings",
    status: "wishlist",
    category: "jewelry",
    colorFamily: "mustard",
    colorName: "Warm Gold",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["statement", "elevated", "tropical"],
    decision: "wishlist",
    priorityTier: "color-builders",
    purchaseOrder: 12,
    duplicateRisk: "medium",
    closetGap: "accessory",
    priorityScore: 7,
    outfitPotential: 8,
    closetImpactScore: 7,
    currentPrice: 6.99,
    targetPrice: 5,
    lowestPrice: 6.49,
    priceWatch: false,
    priceHistory: [
      { date: "2026-06-01", price: 7.99 },
      { date: "2026-06-08", price: 6.99 },
      { date: "2026-06-15", price: 6.99 },
    ],
    notes: "Small statement piece that can make basics feel more Caribbean and styled.",
  },
  {
    id: "wish-013",
    name: "Mustard Satin Blouse",
    status: "wishlist",
    category: "top",
    colorFamily: "mustard",
    colorName: "Muted Mustard",
    size: "M",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["statement", "work", "tropical"],
    decision: "consider",
    priorityTier: "color-builders",
    purchaseOrder: 13,
    duplicateRisk: "low",
    closetGap: "color",
    priorityScore: 7,
    outfitPotential: 7,
    closetImpactScore: 7,
    currentPrice: 17.99,
    targetPrice: 13,
    lowestPrice: 15.99,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 19.99 },
      { date: "2026-06-08", price: 17.99 },
      { date: "2026-06-15", price: 17.99 },
    ],
    notes: "Good color direction if the fabric does not look too shiny or cheap.",
  },
  {
    id: "wish-014",
    name: "Forest Green Blouse",
    status: "wishlist",
    category: "top",
    colorFamily: "olive",
    colorName: "Forest Green",
    size: "M",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "work", "elevated"],
    decision: "wishlist",
    priorityTier: "color-builders",
    purchaseOrder: 14,
    duplicateRisk: "low",
    closetGap: "color",
    priorityScore: 8,
    outfitPotential: 8,
    closetImpactScore: 8,
    currentPrice: 16.99,
    targetPrice: 12,
    lowestPrice: 15.49,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 18.99 },
      { date: "2026-06-08", price: 16.99 },
      { date: "2026-06-15", price: 16.99 },
    ],
    notes: "A strong color builder for office looks without being loud.",
  },
  {
    id: "wish-015",
    name: "Statement Blue Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "blue",
    colorName: "Deep Blue",
    size: "M",
    brand: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["statement", "work"],
    decision: "consider",
    priorityTier: "statement-review",
    purchaseOrder: 15,
    duplicateRisk: "low",
    closetGap: "statement",
    priorityScore: 5,
    outfitPotential: 5,
    closetImpactScore: 5,
    currentPrice: 34.99,
    targetPrice: 24,
    lowestPrice: 32.99,
    priceWatch: false,
    priceHistory: [
      { date: "2026-06-01", price: 36.99 },
      { date: "2026-06-08", price: 34.99 },
      { date: "2026-06-15", price: 34.99 },
    ],
    notes: "Potential statement piece, but lower priority than warm Dark Autumn colors.",
  },
];
