import type { WishlistItem } from "@/types/wardrobe";

export const mockWishlistItems: WishlistItem[] = [
  {
    id: "wishlist-001",
    name: "Camel Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "camel",
    colorName: "Warm Camel",
    size: "M",
    source: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "work", "elevated"],
    decision: "buy-priority",
    priorityTier: "foundation-buys",
    purchaseOrder: 1,
    duplicateRisk: "low",
    closetGap: "workwear",
    priorityScore: 9,
    outfitPotential: 9,
    closetImpactScore: 10,
    currentPrice: 28.99,
    targetPrice: 22,
    lowestPrice: 24.49,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 32.99 },
      { date: "2026-06-08", price: 29.99 },
      { date: "2026-06-15", price: 24.49 },
      { date: "2026-06-22", price: 28.99 },
    ],
    notes: "Strong capsule builder. Adds warmth without duplicating black or beige.",
  },
  {
    id: "wishlist-002",
    name: "Burgundy Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "burgundy",
    colorName: "Warm Burgundy",
    size: "M",
    source: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "statement", "work"],
    decision: "wishlist",
    priorityTier: "color-builders",
    purchaseOrder: 2,
    duplicateRisk: "low",
    closetGap: "color",
    priorityScore: 8,
    outfitPotential: 8,
    closetImpactScore: 9,
    currentPrice: 31.49,
    targetPrice: 24,
    lowestPrice: 27.99,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 35.99 },
      { date: "2026-06-08", price: 31.49 },
      { date: "2026-06-15", price: 27.99 },
      { date: "2026-06-22", price: 31.49 },
    ],
    notes: "Adds intentional color and works with brown, cream, camel, denim, and black.",
  },
  {
    id: "wishlist-003",
    name: "Olive Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "olive",
    colorName: "Muted Olive",
    size: "M",
    source: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["classic", "tropical", "work"],
    decision: "wishlist",
    priorityTier: "color-builders",
    purchaseOrder: 3,
    duplicateRisk: "low",
    closetGap: "color",
    priorityScore: 8,
    outfitPotential: 8,
    closetImpactScore: 8,
    currentPrice: 26.99,
    targetPrice: 21,
    lowestPrice: 23.99,
    priceWatch: true,
    priceHistory: [
      { date: "2026-06-01", price: 29.99 },
      { date: "2026-06-08", price: 26.99 },
      { date: "2026-06-15", price: 23.99 },
      { date: "2026-06-22", price: 26.99 },
    ],
    notes: "Aligned with Dark Autumn and adds tropical versatility.",
  },
  {
    id: "wishlist-004",
    name: "Statement Blue Blazer",
    status: "wishlist",
    category: "outerwear",
    colorFamily: "blue",
    colorName: "Statement Blue",
    size: "M",
    source: "SHEIN",
    productUrl: "https://www.shein.com/",
    vibes: ["statement", "work"],
    decision: "consider",
    priorityTier: "statement-review",
    purchaseOrder: 4,
    duplicateRisk: "medium",
    closetGap: "statement",
    priorityScore: 6,
    outfitPotential: 5,
    closetImpactScore: 5,
    currentPrice: 34.99,
    targetPrice: 24,
    lowestPrice: 30.99,
    priceWatch: false,
    priceHistory: [
      { date: "2026-06-01", price: 38.99 },
      { date: "2026-06-08", price: 34.99 },
      { date: "2026-06-15", price: 30.99 },
      { date: "2026-06-22", price: 34.99 },
    ],
    notes: "Could be fun, but needs enough outfit combinations before buying.",
  },
];
